---
all:
  vars:
    ansible_user: isucon
  hosts:
    isucon13-1:
      ansible_host: 18.182.98.181
    isucon13-2:
      ansible_host: 57.181.162.58
    isucon13-3:
      ansible_host: 18.178.177.82
