---
all:
  vars:
    ansible_user: isucon
  hosts:
    isucon13-1:
      ansible_host: 13.112.77.213
    isucon13-2:
      ansible_host: 35.73.148.82
    isucon13-3:
      ansible_host: 52.68.217.204
