---
all:
  vars:
    ansible_user: isucon
  hosts:
    isucon13-1:
      ansible_host: 54.248.76.214
    isucon13-2:
      ansible_host: 54.199.204.171
    isucon13-3:
      ansible_host: 13.114.143.57
